web.port=8080
web.session.secret=change-me
web.theme=default
web.theme.directory=themes
web.upload.directory=uploads
web.site.name=Habbo
web.web-gallery.path=http://localhost/web-gallery
web.admin.email=admin@starling.local
web.admin.password=admin123!
db.host=127.0.0.1
db.port=3306
db.name=starling
db.username=root
db.password=verysecret
db.params=useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
